[Seat:*]
autologin-guest=false
autologin-user=
autologin-user-timeout=0
greeter-setup-script=/usr/bin/xset s activate
greeter-hide-users=true
inactive-timeout=300
inactive-action=lock

#greeter-allow-guest=false
#user-session=mint